plugins:
- name: tgsend-linux
  os: linux
  arch: amd64
  url: "https://github.techoc.workers.dev/https://github.com/mritd/tgsend/releases/download/v1.0.1/tgsend_linux_amd64"
  desc: "一个 Telegram 推送的小工具，用于调用 Bot API 发送告警等"
  bin: tgsend
- name: tgsend-darwin
  os: darwin
  arch: amd64
  url: "https://github.techoc.workers.dev/https://github.com/mritd/tgsend/releases/download/v1.0.1/tgsend_darwin_amd64"
  desc: "一个 Telegram 推送的小工具，用于调用 Bot API 发送告警等"
  bin: tgsend