version: 1.0
plugins:
- name: helm
  version: v3.7.1
  homepage: "https://helm.sh"
  desc: "The Kubernetes Package Manager"
  bin: helm
  symlink: true
  url:
  - os: linux
    arch: amd64
    url: https://github.com/helm/helm/releases/download/${version}/helm-${version}-linux-amd64.tar.gz
    sha256: ""
- name: k3d
  version: v5.0.3
  homepage: "https://github.com/rancher/k3d"
  desc: "Little helper to run Rancher Lab's k3s in Docker"
  bin: k3d
  url:
  - os: darwin
    arch: amd64
    url: https://github.com/rancher/k3d/releases/download/${version}/k3d-darwin-amd64
    sha256: ""
  - os: darwin
    arch: arm64
    url: https://github.com/rancher/k3d/releases/download/${version}/k3d-darwin-arm64
    sha256: ""
  - os: linux
    arch: amd64
    url: https://github.com/rancher/k3d/releases/download/${version}/k3d-linux-amd64
    sha256: ""
- name: brook
  version: v20210701
  homepage: "https://github.com/txthinking/brook"
  desc: "跨平台的强加密无特征的无配置的代理软件"
  bin: brook
  url:
  - os: darwin
    arch: amd64
    url: https://github.com/txthinking/brook/releases/download/${version}/brook_darwin_amd64
    sha256: ""
  - os: darwin
    arch: arm64
    url: https://github.com/txthinking/brook/releases/download/${version}/brook_darwin_arm64
    sha256: ""
  - os: linux
    arch: amd64
    url: https://github.com/txthinking/brook/releases/download/${version}/brook_linux_amd64
    sha256: ""
