version: 1.0
plugins:
- name: tgsend
  version: v1.0.1
  homepage: "https://github.com/mritd/tgsend"
  desc: "一个 Telegram 推送的小工具，用于调用 Bot API 发送告警等"
  bin: tgsend
  url:
  - os: linux
    arch: amd64
    url: https://github.com/mritd/tgsend/releases/download/${version}/tgsend_linux_amd64
    sha256: ""
  - os: darwin
    arch: amd64
    url: https://github.com/mritd/tgsend/releases/download/${version}/tgsend_darwin_amd64
    sha256: ""
- name: mizu
  version: 0.16.0
  homepage: "https://github.com/up9inc/mizu"
  desc: "API traffic viewer for Kubernetes"
  bin: mizu
  url:
  - os: linux
    arch: amd64
    url: https://github.com/up9inc/mizu/releases/download/${version}/mizu_linux_amd64
    sha256: ""
  - os: darwin
    arch: amd64
    url: https://github.com/up9inc/mizu/releases/download/${version}/mizu_darwin_amd64
    sha256: ""
